apiVersion: v1
kind: Service
metadata:
  name: registry-{{ .Values.instance }}
  namespace: registry
spec:
  selector:
    app.kubernetes.io/name: registry
    neco.cybozu.io/registry: {{ .Values.instance }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
