apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- argocd-config.yaml
- grafana-sandbox.yaml
- tenants
patchesStrategicMerge:
- argocd-ingress.yaml
- argocd.yaml
- bmc-reverse-proxy.yaml
- cert-manager.yaml
- coil.yaml
- customer-egress.yaml
- elastic.yaml
- external-dns.yaml
- meows.yaml
- ingress.yaml
- init-template.yaml
- kube-metrics-adapter.yaml
- local-pv-provisioner.yaml
- logging.yaml
- metallb.yaml
- monitoring.yaml
- namespaces.yaml
- neco-admission.yaml
- network-policy.yaml
- pod-security-admission.yaml
- pvc-autoresizer.yaml
- rook.yaml
- sandbox.yaml
- sealed-secrets.yaml
- secrets.yaml
- session-log.yaml
- team-management.yaml
- teleport.yaml
- topolvm.yaml
