apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
commonLabels:
  deployVersion: v1
nameSuffix: -old
resources:
  - generated/apps-v1.Deployment-distributor.yaml
  - generated/apps-v1.Deployment-query-frontend.yaml
  - generated/apps-v1.Deployment-table-manager.yaml
  - generated/apps-v1.StatefulSet-compactor.yaml
  - generated/apps-v1.StatefulSet-ingester.yaml
  - generated/apps-v1.StatefulSet-memcached-frontend.yaml
  - generated/apps-v1.StatefulSet-memcached-index-queries.yaml
  - generated/apps-v1.StatefulSet-memcached.yaml
  - generated/apps-v1.StatefulSet-querier.yaml
  - generated/policy-v1beta1.PodDisruptionBudget-loki-ingester-pdb.yaml
  - generated/v1.ConfigMap-loki.yaml
  - generated/v1.ConfigMap-overrides.yaml
  - generated/v1.Service-distributor.yaml
  - generated/v1.Service-ingester.yaml
  - generated/v1.Service-memcached-frontend.yaml
  - generated/v1.Service-memcached-index-queries.yaml
  - generated/v1.Service-memcached.yaml
  - generated/v1.Service-querier.yaml
  - generated/v1.Service-query-frontend.yaml
  - generated/v1.Service-table-manager.yaml
patchesStrategicMerge:
  - patch.yaml
