apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - ./upstream
  - ./obc.yaml
  - ./service.yaml
images:
  - name: quay.io/cybozu/memcached
    newTag: 1.6.10.1
  - name: quay.io/cybozu/memcached-exporter
    newTag: 0.9.0.3
  - name: quay.io/cybozu/loki
    newTag: 2.3.0.1
