apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/upstream
  - clusterrolebinding
  - cluster.yaml
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
namespace: ceph-poc-2
