apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - ./ceph-object-store/debug.yaml
patchesJson6902:
- target:
    group: ceph.rook.io
    version: v1
    kind: CephCluster
    name: ceph-ssd
    namespace: ceph-ssd
  patch: |-
    - op: replace
      path: /spec/resources/osd/requests/cpu
      value: 300m
    - op: replace
      path: /spec/resources/crashcollector/requests/cpu
      value: 300m
    - op: replace
      path: /spec/mon/volumeClaimTemplate/spec/resources/requests/storage
      value: 3Gi
    - op: replace
      path: /spec/storage/storageClassDeviceSets/0/count
      value: 5
    - op: replace
      path: /spec/storage/storageClassDeviceSets/0/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 10Gi
- target:
    group: ceph.rook.io
    version: v1
    kind: CephCluster
    name: ceph-object-store
    namespace: ceph-object-store
  patch: |-
    - op: replace
      path: /spec/resources/osd/requests/cpu
      value: 300m
    - op: replace
      path: /spec/resources/crashcollector/requests/cpu
      value: 300m
    - op: replace
      path: /spec/mon/volumeClaimTemplate/spec/resources/requests/storage
      value: 3Gi
    - op: replace
      path: /spec/storage/storageClassDeviceSets/0/count
      value: 3
    - op: replace
      path: /spec/storage/storageClassDeviceSets/1/count
      value: 3
    - op: replace
      path: /spec/storage/storageClassDeviceSets/1/volumeClaimTemplates/0/spec/resources/requests/storage
      value: 5Gi
- target:
    group: apps
    version: v1
    kind: Deployment
    name: rook-ceph-operator
    namespace: ceph-ssd
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: DEBUG
- target:
    group: apps
    version: v1
    kind: Deployment
    name: rook-ceph-operator
    namespace: ceph-object-store
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/2/value
      value: DEBUG
