apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vmalertmanager-largeset.yaml
  - vmalertmanager-smallset.yaml
  - vmalertmanager-app-csa-monitoring.yaml
  - vmalertmanager-app-cybozu-com-mysql.yaml
  - vmalertmanager-app-monitoring.yaml
