apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  # Strategic merge patch is currently failed.
  # Now, we use inline patch.
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
    target:
      kind: Deployment|StatefulSet
      name: distributor|query-frontend|compactor|ingester|memcached|memcached-frontend|memcached-index-queries|querier|table-manager
patchesJSON6902:
  # Temporary configuration for storage performance measurement
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: logging-promtail
      namespace: logging
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations/-
        value:
          key: "csa/exclude_noisy_neighbor"
          operator: "Exists"
      - op: add
        path: /spec/template/spec/tolerations/-
        value:
          key: "neco/exclude_noisy_neighbor"
          operator: "Exists"
  - target:
      group: apps
      version: v1
      kind: DaemonSet
      name: loki-canary
      namespace: logging
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations/-
        value:
          key: "csa/exclude_noisy_neighbor"
          operator: "Exists"
      - op: add
        path: /spec/template/spec/tolerations/-
        value:
          key: "neco/exclude_noisy_neighbor"
          operator: "Exists"
