apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - includeCRDs: true
    name: promtail
    namespace: logging
    releaseName: logging
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
    version: 4.2.0
namespace: logging
