apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- includeCRDs: true
  name: rook-ceph
  namespace: ceph-ssd
  releaseName: rook-release
  repo: https://charts.rook.io/release
  valuesFile: values.yaml
  valuesInline:
    csi:
      rbdGrpcMetricsPort: 29090
      rbdLivenessMetricsPort: 29080
  version: v1.8.3
resources:
  - ../toolbox
  - cephblockpool.yaml
  - cluster.yaml
  - configmap.yaml
  - namespace.yaml
  - pool-device-health-metrics.yaml
namespace: ceph-ssd
patches: # Strategic Merge Patch
  # Delete manifests of ClusterRole, ClusterRoleBinding and CustomResourceDefinition
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ClusterRole
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: ClusterRoleBinding
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: CustomResourceDefinition
