apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - grafana-operator/httpproxy.yaml
  - victoriametrics/rules/network-policy-alertrule.yaml
  - victoriametrics/rules/network-policy-scrape.yaml
patchesStrategicMerge:
  - grafana-operator/grafana.yaml
  - pushgateway/httpproxy.yaml
  - heartbeat.yaml
  - ingress-health/httpproxy.yaml
  - victoriametrics/vmalertmanager.yaml
  - victoriametrics/vmsingle-smallset.yaml
  - victoriametrics/vmcluster-largeset.yaml
configMapGenerator:
  - name: vmalertmanager
    behavior: merge
    files:
      - victoriametrics/env.template
