apiVersion: apps/v1
kind: Deployment
metadata:
  name: neco-admission
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: neco-admission
          args:
            - --cert-dir=/certs
            - --httpproxy-default-class=forest
            - --zap-stacktrace-level=panic
            - --valid-image-prefix=quay.io/cybozu/
            - --valid-image-prefix=quay.io/neco_test/ # test for registry mirror
            - --valid-image-prefix=quay.io/topolvm/
            - --valid-image-prefix=ghcr.io/cybozu/
            - --valid-image-prefix=ghcr.io/cybozu-go/
            - --valid-image-prefix=ghcr.io/cybozu-private/
            - --valid-image-prefix=docker.elastic.co/
            - --valid-image-prefix=quay.io/gravitational/teleport-ent
            - --valid-image-prefix=quay.io/gravitational/teleport
            - --valid-image-prefix=gcr.io/datadoghq/agent
            - --valid-image-prefix=k8s.gcr.io/sig-storage/,quay.io/cephcsi/
