# A scheduler extender for TopoLVM
scheduler:
  # scheduler.affinity -- Specify affinity on the Deployment or DaemonSet.
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: cke.cybozu.com/master
              operator: Exists

  # scheduler.tolerations -- Specify tolerations on the Deployment or DaemonSet.
  ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: cke.cybozu.com/master

# lvmd service
lvmd:
  # lvmd.deviceClasses -- Specify the device-class settings.
  deviceClasses:
    - name: ssd
      volume-group: vg1
      default: true

  # lvmd.nodeSelector -- Specify nodeSelector.
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector:
    cke.cybozu.com/role: cs

  # lvmd.updateStrategy -- Specify updateStrategy.
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 35%
    type: RollingUpdate
  
  # Temporary configuration for storage performance measurement
  tolerations:
    - key: "csa/exclude_noisy_neighbor"
      operator: "Exists"
    - key: "neco/exclude_noisy_neighbor"
      operator: "Exists"

# CSI node service
node:
  # node.nodeSelector -- Specify nodeSelector.
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  nodeSelector:
    cke.cybozu.com/role: cs

  # node.updateStrategy -- Specify updateStrategy.
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 35%
    type: RollingUpdate
  
  # Temporary configuration for storage performance measurement
  tolerations:
    - key: "csa/exclude_noisy_neighbor"
      operator: "Exists"
    - key: "neco/exclude_noisy_neighbor"
      operator: "Exists"

# storageClasses -- Whether to create storageclass(s)
# ref: https://kubernetes.io/docs/concepts/storage/storage-classes/
storageClasses:
  - name: topolvm-provisioner  # Defines name of storage classe.
    storageClass:
      # Supported filesystems are: ext4 and xfs.
      fsType: xfs
      # reclaimPolicy
      reclaimPolicy:  # Delete
      # Additional annotations
      annotations:
        resize.topolvm.io/enabled: "true"
      # Default storage class for dynamic volume provisioning
      # ref: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning
      isDefaultClass: false
      # volumeBindingMode can be either WaitForFirstConsumer or Immediate. WaitForFirstConsumer is recommended because TopoLVM cannot schedule pods wisely if volumeBindingMode is Immediate.
      volumeBindingMode: WaitForFirstConsumer
      # enables CSI drivers to expand volumes. This feature is available for Kubernetes 1.16 and later releases.
      allowVolumeExpansion: true
      additionalParameters: {}
      # "topolvm.cybozu.com/device-class": "ssd"
  - name: topolvm-flash1-xfs  # Defines name of storage classe.
    storageClass:
      # Supported filesystems are: ext4 and xfs.
      fsType: xfs
      # reclaimPolicy
      reclaimPolicy:  # Delete
      # Additional annotations
      annotations:
        resize.topolvm.io/enabled: "true"
      # Default storage class for dynamic volume provisioning
      # ref: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning
      isDefaultClass: false
      # volumeBindingMode can be either WaitForFirstConsumer or Immediate. WaitForFirstConsumer is recommended because TopoLVM cannot schedule pods wisely if volumeBindingMode is Immediate.
      volumeBindingMode: WaitForFirstConsumer
      # enables CSI drivers to expand volumes. This feature is available for Kubernetes 1.16 and later releases.
      allowVolumeExpansion: true
      additionalParameters: {}
      # "topolvm.cybozu.com/device-class": "ssd"
  - name: topolvm-flash1-ext4  # Defines name of storage classe.
    storageClass:
      # Supported filesystems are: ext4 and xfs.
      fsType: ext4
      # reclaimPolicy
      reclaimPolicy:  # Delete
      # Additional annotations
      annotations:
        resize.topolvm.io/enabled: "true"
      # Default storage class for dynamic volume provisioning
      # ref: https://kubernetes.io/docs/concepts/storage/dynamic-provisioning
      isDefaultClass: false
      # volumeBindingMode can be either WaitForFirstConsumer or Immediate. WaitForFirstConsumer is recommended because TopoLVM cannot schedule pods wisely if volumeBindingMode is Immediate.
      volumeBindingMode: WaitForFirstConsumer
      # enables CSI drivers to expand volumes. This feature is available for Kubernetes 1.16 and later releases.
      allowVolumeExpansion: true
      additionalParameters: {}
      # "topolvm.cybozu.com/device-class": "ssd"

podSecurityPolicy:
  # podSecurityPolicy.create -- Enable pod security policy.
  ## ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
  create: false

controller:
  podDisruptionBudget:
    # podDisruptionBudget.enabled -- Enable podDisruptionBudget.
    enabled: true

priorityClass:
  # priorityClass.enabled -- Enable priorityClass.
  enabled: true
  # priorityClass.name -- Set priorityClass name.
  name: "node-bound"
