apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- upstream/controller.yaml

patchesStrategicMerge:
- deployment.yaml

images:
  - name: quay.io/bitnami/sealed-secrets-controller
    newName: quay.io/cybozu/sealed-secrets
    newTag: 0.17.0.1
