apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-config-override
  namespace: ceph-object-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  # this is patched by overlays, please check overlays if you update it.
  config: |
    [mgr]
    ; Suppress the folowing warning.
    ;
    ; ```
    ; health: HEALTH_WARN
    ;        1 pools have many more objects per pg than average
    ; ```
    mon_pg_warn_max_object_skew = 0
    [client]
    rgw_dynamic_resharding = false
