apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../upstream
  - clusterrolebinding
  - cephobjectstore.yaml
  - cluster.yaml
  - configmap.yaml
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
namespace: ceph-object-store
