apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../poc/ceph-poc
  - ../../poc/ceph-poc-2
  - ./ceph-hdd/httpproxy.yaml
  - ./ceph-object-store/httpproxy.yaml
patchesJson6902:
  - target:
      group: ceph.rook.io
      version: v1
      kind: CephCluster
      name: ceph-ssd
      namespace: ceph-ssd
    patch: |-
      - op: replace
        path: /spec/storage/storageClassDeviceSets/0/count
        value: 43
